const data = {
  meta: {
    name: "Jacob Blakely",
    title: "Senior Full Stack Software Engineer",
    contact: {
      email: "jacobmblakely@gmail.com",
      github: "codekirei",
      linkedin: "jacob-blakely",
    },
  },
  bio: "I specialize in making complex things simple. I have years of experience delivering elegant software solutions across the entire stack, with a focus on the web and the command line, and have experience both leading and contributing to remote software teams to ship products to millions of users. Comfortable in customer-facing roles. Excellent communicator.",
  skills: {
    languages: [
      "Typescript",
      "Node.js",
      "Python",
      "Lua",
      "Go",
      "CSS",
      "SQL",
      "Shell",
    ],
    frameworks: [
      "React",
      "Redux",
      "Next.js",
      "Jest",
      "Django",
      "REST Framework",
      "Kubernetes",
    ],
    other: [
      "Git",
      "AWS",
      "Microservices",
      "GraphQL",
      "API Design and Development",
      "Webhooks",
      "Database Architecture",
      "Linux Administration",
      "Open Source Development",
      "Technical Documentation",
      "Customer Support",
      "Responsive UI",
      "TDD",
      "CI/CD",
    ],
  },
};
